### ISSUE TITLE
Follow steps to install Fast AI on Azure ML without success

### ISSUE THREAD

**Issue by ChrCoello** [Azure/AzureML-fastai#11]
Trying to follow the manual Fast AI environment setup to get an updated version of fastai on the compute -> [https://github.com/Azure/AzureML-fastai#manual-fastai-environment-setup](https://github.com/Azure/AzureML-fastai#manual-fastai-environment-setup)
Compute type : STANDARD_F4S_V2 (4 Cores, 8 GB RAM, 32 GB Disk)
All steps work until `conda install -y -c fastai -c pytorch fastai`

Error: 

> (fastaienv) azureuser@cc-cmp01:~/cloudfiles/code/Users/christopher.coello$ conda install -y -c fastai -c pytorch fastai
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                        
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions

**Comment by AbeOmor** [comment]
Hi @ChrCoello, Are you still running into this issue? I was able to repro on a STANDARD_F4S_V2. There seem to be some incompatibility issues with that compute. Can you try a different SKU like Standard_DS2_v2?

**Comment by ChrCoello** [comment]
Same configuration than previosuly  -> I have now run the step `conda install -y -c fastai -c pytorch fastai` with success. Closing this issue.
